### ISSUE TITLE
Windows scaling.

### ISSUE THREAD

**Issue by MrPillze** [Robbbert/store1#10]
Hi there i have a large screen running in 4k and to fix the tiny ui i use windows scaling, arcade64 has trouble with windows scaling and shows up tiny untill i override windows scaling and let the system do it in compatibility of the .exe but the setting doesnt save consistently. would there be any chance of windows scaling support for this great version of mame :)

**Comment by Robbbert** [comment]
This sounds like a Windows 10 thing.

I do not use Windows 10, and I do not possess a 4k monitor, so it's impossible for me to work on this.

**Comment by tastyratz** [comment]
I just wanted to comment here as I have the same problem.
The text in arcade is impossibly small rendering it completely unusable on high resolution displays.

Windows scaling feature works at any resolution.

A way to fix this outside of windows 10 scaling, however, would just simply have selectable font sizing and/or a small/large/xl preset in the UI?

As it sits, I would say the text looks like it's 4point on my display.


![image](https://user-images.githubusercontent.com/657895/93034706-f5aabc80-f608-11ea-83ed-42e86ff941ff.png)
