### ISSUE TITLE
instable version (0.208)

### ISSUE THREAD

**Issue by Titofff** [Robbbert/store1#11]
I have crash sometime.

When i have crash, i loose my config for my mapped keys on my gamepad.

Sometimes(when i have crash), i have a black screen when i run a game.

For recover a good version (with my last config)i must copy my backup of arcade to installed version and all is fine for while.

**Comment by Robbbert** [comment]
After copying, make the new file read-only. Then the emulator cannot change it.

**Comment by Titofff** [comment]
Hello.

 

I’m little confused…

 

I found the problem.

 

It was my old microsoft controller, so I took another controller and it works fine now without losing configuration.

 

Christophe. 😉

 

De : Robert <notifications@github.com> 
Envoyé : mardi 23 avril 2019 18:40
À : Robbbert/store1 <store1@noreply.github.com>
Cc : Titofff <christophe.l1970@gmail.Com>; Author <author@noreply.github.com>
Objet : Re: [Robbbert/store1] instable version (0.208) (#11)

 

After copying, make the new file read-only. Then the emulator cannot change it.
