### ISSUE TITLE
Black Screen after loading game.

### ISSUE THREAD

**Issue by bonovox2k** [Robbbert/store1#13]
after few trys to play killer instinct sometimes boot in black screen with audio, in black screen, look the video i have made to show in https://youtu.be/uiRIXtI1StM

**Comment by bonovox2k** [comment]
Killer Instinct 2 have the same issue!

**Comment by Robbbert** [comment]
I only have an older chd, but it appears to work fine.

Try deleting your old diff file.

**Comment by bonovox2k** [comment]
The installed version are fresh install, any way just delete the kinst.dif don´t fix the problem. the version of kinst.chd have the crc  35d59b6f, thanks a lot Mr Robbbert!

**Comment by Robbbert** [comment]
What OS are you using? What video card? Using ARCADE32, or ARCADE64?
Some suggestions you could try..
1. Change video mode to opengl
2. See what happens with standard MAME from the mamedev site
3. Retrieve verbose.log and paste here.

**Comment by bonovox2k** [comment]
Lets do this! OS = Windows 10 Pro x64, Nvidia Geforce 1070 and 1080, using arcade32 the emulator close sometimes after load killer instinct unexpected close emulator, on arcade64 some times the rom load with intro sound and stop in black screen stucked! i try mamedev version 64 with ugly menu and runs fine without the same troubles of arcade ex FX version... i can attach the 64 version of verbose in time of stuck black screen... THE BUGS OCCURS IN THE 1s RUN TRY or OPEN/CLOSE/OPEN multiple times to get this error... i can kick can be a memmory allocation issue... i don´t know! you are the man with knowledge to investigate and maybe fix this problem.
[verbose32.log](https://github.com/Robbbert/store1/files/3193432/verbose32.log)
[verbose64.log](https://github.com/Robbbert/store1/files/3193433/verbose64.log)

**Comment by Robbbert** [comment]
We've been getting reports of random black screen when using Windows 10 with nVidia graphics and MAME.
A solution that worked for one person was to use 60hz instead of 70. Another person had crashes until he removed nvidia custom setup.
Please check your nvidia settings and remove anything that isn't out of the box.

**Comment by bonovox2k** [comment]
i don´t have custom profile for mame or anything, in machine with nvidia 1070 i have a 1080p 60hz locked monitor and the machine with 1080 i have 2k gsync 144hz  monitor in both cases i have the same issue, 
I never noticed other roms just chds of killer instinct 1 and 2 and probably others CHDS.

**Comment by Robbbert** [comment]
I don't have any other suggestions.

**Comment by bonovox2k** [comment]
Thanks a lot! i´m very happy with your support! If you are updated, about this issue please let me know! 
for now! Thanks to your project arcade, is my favorite mame arcade distro ever!

**Comment by Robbbert** [comment]
Thanks :)  I'll close this for now, and reopen it if a solution comes along.

**Comment by bonovox2k** [comment]
Robbbert, i have made a few tests and just place here results...
Mame Arcade64 + Killer Instinct 1 e 2 (some times black screen in boot)
Mame Arcade64 + cps1 games (for example) (works ok)
Mame64 from mamedev oficial, + killer instinct 1 e 2 (works ok) 
seems to be a arcade + chd games issue black screen, nothing to do with nvidia graphics card.

i do minimum of 100 runs for each, example run by command line, escape, run again...
