### ISSUE TITLE
ARCADE64 0.212 (64-bit) 

### ISSUE THREAD

**Issue by Cibomatto2002** [Robbbert/store1#14]
When launching a game I get this error.
![Capture2-26-2019-1 00 36 AM4-13-2019-1 36 54 PM8-1-2019-1 17 09 AM](https://user-images.githubusercontent.com/21169038/62269974-558cd680-b3fa-11e9-9def-a083eb5de77e.jpg)

**Comment by Robbbert** [comment]
https://www.1emulation.com/forums/topic/36177-arcade-0212/
