### ISSUE TITLE
Some NeoGeo games are stuck to WORK RAM TEST

### ISSUE THREAD

**Issue by iori3000** [Robbbert/store1#2]
I found these NeoGeo games are stuck to WORK RAM TEST on boot
Magical Drop III
Money Puzzle Exchanger

I didn't test not so much other NeoGeo games,
Some NeoGeo games are no problem.

It seems that other MAMEs have no problem like this except ARCADE MAME 0.197

**Comment by ArcadeUser** [comment]
I'm also having this problem.   I would say only half of the Neo Geo based games actually launch, even with a 100% known good romset, and a totally clean install.

**Comment by Cornervizion** [comment]
Likewise... having spoke to other MAME users, the Arcade build is the only one that seems to have this issue.

**Comment by Robbbert** [comment]
This was fixed on 8th of May.
