### ISSUE TITLE
bios not working

### ISSUE THREAD

**Issue by krusso222** [Robbbert/store1#20]
hi sega lindbergh bios showing bad when they are good

**Comment by Robbbert** [comment]
Insufficient information.

**Comment by krusso222** [comment]
when i run an audit arcade shows that that file is bad in ver 221 so i ran ver 220 and arcade says it good was that file changed   ken

**Comment by Robbbert** [comment]
It shows good for me. What exactly does it say?

**Comment by krusso222** [comment]
it says im missing the chd but i know its there

**Comment by Robbbert** [comment]
You'll have to make sure it's in your rompath. Check your mame.ini and your ini\mame.ini to make sure they are correct.

**Comment by krusso222** [comment]
ichecked every thing is ok this is the only error

**Comment by Robbbert** [comment]
As I say, it worked for me, so there's nothing else I can suggest.
By the way, the bios doesn't work, you'll get a fatal error if you try running it.
In fact, I will remove the entire driver out of Arcade64, since none of the games work. That will fix your problem.

**Comment by krusso222** [comment]
ok thank you for trying for me i thank you for arcade64       ken
