### ISSUE TITLE
Arcade64 0.198

### ISSUE THREAD

**Issue by steven44** [Robbbert/store1#3]
Hi i have noticed an issue with The Empire Strikes Back rom on Arcade64 0.198.

When the game starts after 5-10 seconds the game crashes back to the insert coin screen. This is an issue with the Arcade64 version of 0.198 as MameUI 0.198 runs it fine (also Arcade64 0.197 ran it fine).

My specs are I5 6600K, 16gig of ram, GTX970 Graphics Card

Thanks in advance.

Kind Regards

Steven

**Comment by Robbbert** [comment]
This is a bug in MAME.

It has been fixed here:
https://github.com/mamedev/mame/commit/8e6b484e860066bd421f2d7fe00fc7a828324ae0
