### ISSUE TITLE
GUI window resetting to the center of the screen on wallpaper change

### ISSUE THREAD

**Issue by zomgugoff** [Robbbert/store1#4]
I know this will sound like a non-issue, but it's been an issue with all MAMEUI variants (except M+GUI) for many years. I use a wallpaper changing program that changes on a timer. When the wallpaper changes, the UI window resets to the center of the screen and looses focus. I don't understand what the relation is, but it's very annoying and it shouldn't be happening. I wouldn't be complaining about this, but M+GUI is crashing on the 0.198 version of ARCADE64, so I can't use it now.

**Comment by Robbbert** [comment]
Sorry, I do not know the answer to this.

If I come across a solution in the future it will be implemented.

Thank you.
