### ISSUE TITLE
Arcade64 v0.201 doesn't excluse Amiga PC 

### ISSUE THREAD

**Issue by taz-nz** [Robbbert/store1#6]
When you create a clrmamepro dat file from latest release of Arcade MAME, it lists a large number of Amiga roms as missing. I don't think they should be required for arcade only MAME.

**Comment by Robbbert** [comment]
The Arcadia games run on Amiga motherboards. The Amiga (particularly the keyboards) was rewritten a week ago and since the code is shared between the pc and arcade games, you now need those roms even though they'll never be used.
