### ISSUE TITLE
some MESS roms are still included when running datfile

### ISSUE THREAD

**Issue by SaucySarah** [Robbbert/store1#7]
Hi, thanks for this awesome 'Arcade' only frontend. It seems though that there are some MESS roms still being incuded when running through ClrMAME. Various Amiga Keyboard Roms, HD Controllers, Action Replay, IDE Controllers etc.

**Comment by Robbbert** [comment]
See issue 6
https://github.com/Robbbert/store1/issues/6

**Comment by SaucySarah** [comment]
ClrMamePro has been asking me to add a lot of non-arcade roms over the last few versions of Arcade64. Like CGA roms which Arcade Database says they were added in MESS 156 and ComX-pl80 which was MESS 154. I'm not sure these are actually needed for MAME ? Or are they ? (There are a lot more).

**Comment by SaucySarah** [comment]
Also, when making a datfile from Arcade64 using ClrMame (-listxml) it tells me SoftwareLists were detected and asks me if I want to import the SoftwareLists. I thought these were for MESS only ?
